# Generated by Django 3.0 on 2021-12-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.CharField(max_length=100000),
        ),
    ]
