# Generated by Django 3.0 on 2021-12-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20211216_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nombre',
            field=models.CharField(max_length=100000),
        ),
    ]
