# Generated by Django 3.0 on 2021-12-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20211216_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(default=12, max_length=100000),
            preserve_default=False,
        ),
    ]
