# Generated by Django 3.0 on 2021-12-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
    ]
